[package]
name = "ThriftChain"
version = "0.1.0"
edition = "2024"
published-at = ""

[addresses]
thriftchain = "_"

[dev-addresses]
thriftchain = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
